### ISSUE TITLE
Favor ver os PR

### ISSUE THREAD

**Issue by ItaloCobains** [onezer00/links-uteis#3]
Fiz um pull request e ainda não fui respondido.

**Comment by onezer00** [comment]
Prontinho @ItaloCobains ... Não tinha visto a notificação do pull requests, mas já fiz o merge.

**Comment by ItaloCobains** [comment]
Imaginei que isso havia acontecido @onezer00, mais de boa. Obg pelo tempo

**Comment by onezer00** [comment]
Inclusive se tiver mais links e quiser compartilhar com a galera vai ser bem legal!
